name: Bangun APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Ambil kode
        uses: actions/checkout@v4
        with:
          submodules: recursive  # ← Ini ambil isi folder Jumble & NetCipher yang kosong tadi!

      - name: Siapkan Java
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Bangun APK
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Simpan APK
        uses: actions/upload-artifact@v4
        with:
          name: APK-HamMumble
          path: app/build/outputs/apk/debug/*.apk
